sudo: required

language: ruby

services:
  - docker

before_install:
- docker build -t ci-sinatra .
- docker run -d -p 127.0.0.1:80:4567 ci-sinatra bundle exec foreman start
- docker ps -a

script:
- docker run ci-sinatra bundle exec rake test
